language: go
go:
  - 1.13.4

git:
  depth: 1

notifications:
  email: false

jobs:
  include:
    - stage: lint & test
      if: (branch = master) AND (type IN (push, pull_request))
    - stage: build
      if: (branch = master) AND (type IN (push, pull_request))
      workspaces:
        create:
          name: ws
      script:
        - touch test.txt
    - stage: package
      if: (branch = master) AND (type = push)
      workspaces:
        use:
          - ws
      script:
        - echo "package on push to master"
        - cat test.txt
    - stage: promote
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      script:
        - echo "promote on tag to master"
        - ./run.sh
