language: go
go:
  - 1.13.4

git:
  depth: 1

notifications:
  email: false

jobs:
  include:
    - stage: lint & test
      if: (branch = master) AND (type IN (push, pull_request))
      script:
        - echo "lint & test"
    - stage: build
      if: (branch = master) AND (type IN (push, pull_request))
      script:
        - echo "build on push or pr"
    - stage: package
      if: (branch = master) AND (type = push)
      script:
        - echo "package on push to master"
    - stage: promote
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      script:
        - echo "promote on tag to master"
        - bash run.sh
